agentAddress udp:161

rocommunity public

sysLocation  Delta-V Flow Test Lab
sysContact   delta-v-admin
sysName      flow-default-testnode-1

# Expose standard MIB-II views (system, interfaces, IP)
view all included .1
access notConfigGroup "" any noauth exact all none none
