---
name: E2E Tests
run-name: End-to-end tests (core, minion, sentinel)

on:
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  e2e-core:
    if: "!contains(github.event.head_commit.message || '', '[skip e2e-tests-core]')"
    strategy:
      fail-fast: false
      matrix:
        shard_idx: [0, 1, 2, 3, 4, 5, 6, 7]
        shards: [8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Restore M2 cache
        uses: actions/cache/restore@v4
        with:
          key: m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
          restore-keys: m2-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
      - name: Quick compile
        run: |
          make quick-compile
      - name: Quick assemble
        run: |
          make quick-assemble
      - name: Run Core End-to-End tests (shard ${{ matrix.shard_idx }})
        run: |
          make core-e2e MAVEN_SHARD_IDX=${{ matrix.shard_idx }} MAVEN_SHARDS=${{ matrix.shards }}
      - name: Publish Core E2E Test Report (shard ${{ matrix.shard_idx }})
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: "Core E2E Test Report (shard ${{ matrix.shard_idx }})"
      - name: Collect test results and logs
        if: always()
        run: |
          make collect-testresults
      - name: Upload Core E2E test artifacts (shard ${{ matrix.shard_idx }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-core-artifacts-${{ matrix.shard_idx }}
          path: |
            target/artifacts/mvn.*.log
            target/artifacts/surefire-reports
            target/artifacts/failsafe-reports
            target/artifacts/recordings
            target/artifacts/smoke-test-*.tar.gz

  e2e-minion:
    if: "!contains(github.event.head_commit.message || '', '[skip e2e-tests-minion]')"
    strategy:
      fail-fast: false
      matrix:
        shard_idx: [0]
        shards: [1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Restore M2 cache
        uses: actions/cache/restore@v4
        with:
          key: m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
          restore-keys: m2-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
      - name: Quick compile
        run: |
          make quick-compile
      - name: Quick assemble
        run: |
          make quick-assemble
      - name: Run Minion End-to-End tests (shard ${{ matrix.shard_idx }})
        run: |
          make minion-e2e MAVEN_SHARD_IDX=${{ matrix.shard_idx }} MAVEN_SHARDS=${{ matrix.shards }}
      - name: Publish Minion E2E Test Report (shard ${{ matrix.shard_idx }})
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: "Minion E2E Test Report (shard ${{ matrix.shard_idx }})"
      - name: Collect test results and logs
        if: always()
        run: |
          make collect-testresults
      - name: Upload Minion E2E test artifacts (shard ${{ matrix.shard_idx }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-minion-artifacts-${{ matrix.shard_idx }}
          path: |
            target/artifacts/mvn.*.log
            target/artifacts/surefire-reports
            target/artifacts/failsafe-reports
            target/artifacts/recordings
            target/artifacts/smoke-test-*.tar.gz

  e2e-sentinel:
    if: "!contains(github.event.head_commit.message || '', '[skip e2e-tests-sentinel]')"
    strategy:
      fail-fast: false
      matrix:
        shard_idx: [0]
        shards: [1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Restore M2 cache
        uses: actions/cache/restore@v4
        with:
          key: m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
          restore-keys: m2-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository
      - name: Quick compile
        run: |
          make quick-compile
      - name: Quick assemble
        run: |
          make quick-assemble
      - name: Run Sentinel End-to-End tests (shard ${{ matrix.shard_idx }})
        run: |
          make sentinel-e2e MAVEN_SHARD_IDX=${{ matrix.shard_idx }} MAVEN_SHARDS=${{ matrix.shards }}
      - name: Publish Sentinel E2E Test Report (shard ${{ matrix.shard_idx }})
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: "Sentinel E2E Test Report (shard ${{ matrix.shard_idx }})"
      - name: Collect test results and logs
        if: always()
        run: |
          make collect-testresults
      - name: Upload Sentinel E2E test artifacts (shard ${{ matrix.shard_idx }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-sentinel-artifacts-${{ matrix.shard_idx }}
          path: |
            target/artifacts/mvn.*.log
            target/artifacts/surefire-reports
            target/artifacts/failsafe-reports
            target/artifacts/recordings
            target/artifacts/smoke-test-*.tar.gz
