---
name: Integration Tests
run-name: Run integration test suite

on:
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  integration-tests:
    if: "!contains(github.event.head_commit.message || '', '[skip integration-tests]')"
    runs-on: [self-hosted, linux, x64]
    strategy:
      fail-fast: false
      matrix:
        shard_idx: [0, 1, 2, 3, 4, 5, 6, 7]
        shards: [8]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Restore Maven repository cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ hashFiles('**/pom.xml') }}-${{ github.sha }}
          restore-keys: |
            m2-${{ hashFiles('**/pom.xml') }}

      - name: Download tarball-core artifact
        uses: actions/download-artifact@v4
        with:
          name: tarball-core
          path: opennms-full-assembly/target

      - name: Compile test classes
        run: |
          make quick-compile

      - name: Assemble for integration tests
        run: |
          make quick-assemble

      - name: Run integration test suite (shard ${{ matrix.shard_idx }})
        run: |
          make integration-tests MAVEN_SHARD_IDX=${{ matrix.shard_idx }} MAVEN_SHARDS=${{ matrix.shards }}

      - name: Publish Integration Test Report (shard ${{ matrix.shard_idx }})
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Integration Test Report (shard ${{ matrix.shard_idx }})

      - name: Collect test results and logs (shard ${{ matrix.shard_idx }})
        if: always()
        run: |
          make collect-testresults

      - name: Persist integration test results (shard ${{ matrix.shard_idx }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-artifacts-${{ matrix.shard_idx }}
          path: |
            target/artifacts/mvn.*.log
            target/artifacts/surefire-reports
            target/artifacts/failsafe-reports
